### ISSUE TITLE
Breaks inline HTML tags in markdown content

### ISSUE THREAD

**Issue by samny** [Mrtenz/gatsby-remark-static-images#3]
I'm using this plugin because I have GIFs in markdown that can't be handled by _gatsby-remark-images_. Since I started to use this plugin I noticed that inline HTML tags in markdown are broken. 

For example with some text wrapped in a span:

```
The <kbd>quick brown fox</kbd> jumps over the lazy dog
```

I get this output, which has the HMTL tag instantly closed:

```
<p>The <kbd></kbd>quick brown fox<kbd></kbd> jumps over the lazy dog</p>
```

I disabled all other remark plugins and could pin down the issue to _gatsby-remark-static-images_.

**Comment by Mrtenz** [comment]
Thank you for reporting this issue. I'm a bit short of time right now, but I'll see what I can do to fix it.
